deb: run migration even if UWSGI is not configured
grouprise can be used without UWSGI.  Thus we should not bind
automatic migration to that specific application server.

diff --git a/debian/grouprise.postinst b/debian/grouprise.postinst
--- a/debian/grouprise.postinst
+++ b/debian/grouprise.postinst
@@ -12,13 +12,10 @@ if [ "$1" = "configure" ]; then
             --home "$DIR_HOME" "$PKG_USER"
     fi
 
-    if [ -f "/etc/uwsgi/apps-enabled/grouprise.ini" ]; then
-        if /usr/bin/stadtctl migrate --no-input >/dev/null; then
-            rm -f "$DIR_ETC/maintenance_mode"
-        else
-            echo "error while executing $PKG_USER migrations. maintenance mode still active" >&2
-        fi
-
+    if /usr/bin/stadtctl migrate --no-input >/dev/null; then
+        rm -f "$DIR_ETC/maintenance_mode"
+    else
+        echo "error while executing $PKG_USER migrations. maintenance mode still active (indicator file: $DIR_ETC/maintenance_mode)" >&2
     fi
 
     chown "$PKG_USER:root" /var/backups/grouprise
