deb: explain failed database backup during package upgrade
The database tool (e.g. `pg_dump`) may be missing, since its package is
only a conditional dependency of grouprise.

See #677

diff --git a/debian/grouprise.preinst b/debian/grouprise.preinst
--- a/debian/grouprise.preinst
+++ b/debian/grouprise.preinst
@@ -15,7 +15,10 @@ if getent passwd "$PKG_USER" >/dev/null; then
 
     if [ -e "$UWSGI_APP_SYMLINK" ]; then
         touch "$DIR_ETC/maintenance_mode"
-        "$CTL_TOOL" database_dump --prefix preinst_auto
+        if ! "$CTL_TOOL" database_dump --prefix preinst_auto; then
+            echo >&2 "Failed to create a database backup.  Maybe the relevant package (see 'grouprise-deb-*') is missing.  Aborting in order to prevent any changes while lacking a database backup."
+            exit 1
+        fi
     fi
 fi
 
